### PR TITLE
Minor fixes to work with Python3

### PR DESCRIPTION
**Pull request by dubnom**
Fixed a unicode issue in setup.py and an accidental reference to PyString_FromString (should have been PyUnicode_FromString in _potrace.c.

These changes fixed issues with Python3 and tested on Python 3.7.3.

### CODE REVIEW

**Comment by lrouch-gpsw** [comment]
Hi, did you try my python 3 fixes in https://github.com/flupke/pypotrace/pull/21?

**Comment by flupke** [comment]
Hi, thank you for the PR. Did you try https://github.com/flupke/pypotrace/pull/21?

**Comment by dubnom** [comment]
I just tried #21 and it seems to work great.  The build time was quite long, but it works.  Any intent to make it Master and release?
Thanks - Mike

**Comment by lrouch-gpsw** [comment]
Hi, just pushed 0.2 on pypi from #21, thanks for contributing :)

**Comment by flupke** [comment]
Hi, just pushed 0.2 on pypi from #21, thanks for contributing :)

**Comment by dubnom** [comment]
Thanks for the push, great stuff.
- Mike

Sent from my iPhone

On Oct 18, 2019, at 6:17 AM, Luper Rouch <notifications@github.com> wrote:

﻿

Closed #23<https://github.com/flupke/pypotrace/pull/23>.

**Pull request closed without merging**
